//---------------------------------------弹窗---------------------------------
const i18nAlert = {
    'zh': {
        alertTitle: '信息',
        alertBtn: '确定',
        cancel: '取消',
        logout: '退出登录成功',
        closeInSeconds: "秒后关闭!",
        yes: "操作成功!",
        successes: "成功!",
        newChannels: "新增渠道",
        mfaVerify: "MFA 验证",
        handlingFeeEditorFixedMode: "手续费编辑-固定模式",
        commissionEditingConditionalMode: "手续费编辑-条件模式",
        landingSuccess: "登陆成功",
        newMerchants: "新增商户",
        editMerchant: "编辑商户",
        switchgear: "启动|禁用",
        switchgearNotice: "正常|异常",
        enable: "启动",
        disable: "禁用",
        close: "关闭",
        all: "全部",
        pleaseSelect: "请选择",
        computing: "确认要保存吗?",
        fillMerchantPublicKey: "请填写商户公钥!",
        reNotification: "点击确认后，该笔还款会再次通知商户，确认进行此操作吗?",
        eighth: "到第",
        common: "共",
        clause: "条",
        loginName: "用户名不能为空",
        password: "密码不能为空",
        verifyCode: "验证码不能为空",
        verifyError: "验证码错误",
        newPwd: "两次密码不一致!",
        editEWallet: "编辑电子钱包",
        addEWallet: "添加电子钱包",
        collection: "归集",
        cloudMachine: "云机操作",
        copyYes: "复制成功!",
        copyNo: "复制失败请手动输入!",
        nonsupport: "不支持直接复制文本到剪贴板!",
        pleaseTxnID: "请输入TxnID!",
        rePayment: "确认要重新付款吗?",
        repaymentConfirmation: "重新付款确定",
        detailRePayment: "确认要重新归集吗?",
        cancalPayment: "确认要取消归集吗?",
        detailRepaymentConfirmation: "代付单重新归集(脚本已上报流水场景)确定",
        detailCancalPaymentConfirmation: "确定取消归集",
        cancellationPayment: "取消付款确定",
        CancelPayment: "确认要取消付款吗?",
        manualConfirmPayment: "人工确认放款",
        manualConfirmPaymentConfirmation: "确认要人工确认放款吗?",
        expeditedPayment: "是否加急",
        expeditedPaymentConfirmation: "确认是否要加急吗?",
        deletion: "删除",
        confirmDeletion: "确认是要删除吗?",
        regainAccount: "恢复钱包",
        confirmRegainAccount: "确认要恢复吗?",
        paymentSuccessRecord: "有付款成功记录,必填填写支付流水号Txid",
        retry: "重新通知",
        retryConfirmation: "确认要重新通知吗?",
        timePrompt: "收款时间不能大于当前时间!",
        debitCard: "代付卡",
        bankCard: "银行卡",
        manualValidation: "人工确认正常",
        confirmationIsNormal: "代收短信人工确认为正常",
        modifyChannel:"编辑渠道",
        collectionConfirmation: "归集到的账户号",
        updateNotice: "修改商户公告",
        designated: "指定商户通知",
        individualHouseholdCollection: "导入个户归集数据"
    },
    'en': {
        alertTitle: 'Information',
        alertBtn: 'OK',
        cancel: 'cancel',
        logout: 'Exit Login Successful',
        closeInSeconds: "Close in seconds!",
        yes: "The operation worked!",
        successes: "successes!",
        newChannels: "New channels",
        mfaVerify: "MFA verification",
        handlingFeeEditorFixedMode: "Handling Fee Edit - Fixed Mode",
        commissionEditingConditionalMode: "Commission editing - Conditional mode",
        landingSuccess: "Landing Success",
        newMerchants: "New Merchants",
        editMerchant: "Edit Merchant",
        switchgear: "Enable|Disable",
        enable: "enable",
        disable: "disable",
        close: "Close",
        all: "All",
        pleaseSelect: "please select",
        computing: "Are you sure you want to save it?",
        fillMerchantPublicKey: "Please fill in the merchant public key!",
        reNotification: "After clicking Confirm, the repayment will notify the merchant again to confirm this operation?",
        eighth: "up to the",
        common: "common",
        clause: "clause",
        loginName: "User name cannot be empty",
        password: "Password cannot be empty",
        verifyCode: "CAPTCHA can't be empty",
        verifyError: "CAPTCHA error",
        newPwd: "Two passwords don't match!",
        editEWallet: "Edit eWallet",
        addEWallet: "Add eWallet",
        collection: "collection",
        cloudMachine: "Cloud machine operation",
        copyYes: "Successful replication!",
        inputPrompt: "The Transaction ID is not valid. It must be 8 or 10 digits+ capital letters",
        copyNo: "Replication failure Please enter manually!",
        nonsupport: "Copying text directly to the clipboard is not supported!",
        pleaseTxnID: "Please enter TxnID!",
        rePayment: "Do you want to make a new payment?",
        detailRePayment: "Are you sure you want to regroup?",
        detailRepaymentConfirmation: "The payment order is collected again (the script has been reported to the pipeline scenario)",
        repaymentConfirmation: "Repayment confirmation",
        cancellationPayment: "Cancellation of payment confirmation",
        CancelPayment: "Are you sure you want to cancel the payment?",
        manualConfirmPayment: "Manual confirmation of lending",
        manualConfirmPaymentConfirmation: "Do you want manual confirmation of the release?",
        expeditedPayment: "Expedited or not",
        expeditedPaymentConfirmation: "Confirming whether or not you want it expedited?",
        deletion: "Delete",
        confirmDeletion: "Is it confirmed that it is to be deleted?",
        regainAccount: "Restore the wallet",
        confirmRegainAccount: "Is it confirmed that you want to restore?",
        paymentSuccessRecord: "Payment success record, must fill in the payment serial number Txid",
        retry: "re-notification",
        retryConfirmation: "Confirmation to be re-notified?",
        timePrompt: "The collection time cannot be longer than the current time!",
        debitCard: "Debit card",
        bankCard: "Bank card",
        manualValidation: "Manual validation",
        confirmationIsNormal: "Receive SMS manual confirmation is normal",
        modifyChannel:"Editorial channel",
        collectionConfirmation: "Collected account number",
        updateNotice: "Amendment to merchant notice",
        designated: "Designated merchant notice",
        switchgearNotice: "Normal|abnormal",
        individualHouseholdCollection: "Import individual household collection data"
    },
    'ban': {
        alertTitle: 'তথ্য',
        alertBtn: 'নির্ধারণ করুন',
        cancel: 'বাতিল করুন',
        logout: 'সফলভাবে বের হয়ে লগ-ইন করা হয়েছে',
        closeInSeconds: "সেকেন্ডে বন্ধ করো!",
        yes: "অপারেশন সফল!",
        successes: "সফল!",
        mfaVerify: "MFA পরীক্ষা করা হচ্ছে",
        newChannels: "নতুন চ্যানেল যোগ করা হয়েছে",
        handlingFeeEditorFixedMode: "ফি সম্পাদনা - ফিক্স মোড",
        commissionEditingConditionalMode: "ফি সম্পাদনা - অবস্থান মোড",
        landingSuccess: "লগ-ইন সফল",
        newMerchants: "New merchants added",
        editMerchant: "সম্পাদনা করুন",
        switchgear: "Enable|Disable",
        enable: "enable",
        disable: "disable",
        close: "বন্ধ করুন",
        // switchgear: "আরম্ভ করুন।নিষ্ক্রিয়",
        all: "সম্পূর্ণ",
        pleaseSelect: "অনুগ্রহ করে নির্বাচন করুন",
        computing: "Are you sure you want to save it?",
        fillMerchantPublicKey: "দয়া করে ব্যবসায়ীর পাবলিক চাবিকে পূরণ করুন!",
        reNotification: "নিশ্চিত করার পরে ব্যবসায়ীকে পুনরায় বিনিময়ের ব্যাপারে জানানো হবে । আপনি কি এই অপারেশনের সাথে চালু করতে নিশ্চিত?",
        eighth: "শেষ পর্যন্ত",
        common: "সাধারণ",
        clause: "স্ট্রিপ",
        loginName: "ব্যবহারকারীর নাম ফাঁকা হতে পারে না",
        password: "পাসওয়ার্ড ফাঁকা হতে পারে না",
        verifyCode: "পরিচিতি কোড ফাঁকা হতে পারে না",
        verifyError: "সার্টিফিকেশন কোড ত্রুটি",
        newPwd: "Two passwords are inconsistent!",
        editEWallet: "ইলেকট্রনিক ওয়ালেট সম্পাদনা করো",
        addEWallet: "ইলেকট্রনিক ওয়ালেট যোগ করো",
        collection: "অজ্ঞাত পলিং",
        cloudMachine: "ক্লাউড অপারেশন",
        copyYes: "সফল কপি করুন!",
        inputPrompt: "Transaction ID বৈধ নয়। এটা অবশ্যই ৮ অথবা ১০ ডিজিট+ রাজধানী চিঠি",
        copyNo: "টকপি করা ব্যর্থ, অনুগ্রহ করে নিজেই লিখুন!",
        nonsupport: "ক্লিপবোর্ডে টেক্সট সরাসরি কপি করা যাচ্ছে না!",
        pleaseTxnID: "অনুগ্রহ করে TxnID লিখুন!",
        rePayment: "আপনি কি নিশ্চিত যে আপনি একটি নতুন পুরস্কার করতে চান?",
        detailRePayment: "আপনি কি নিশ্চিত যে আপনি পুনরুদ্ধার করতে চান?",
        detailRepaymentConfirmation: "প্রতিদানের রিপোর্ট পুনরায় সংগ্রহ করুন (ফ্লিউ সিনেমারির জন্য সংবাদ প্রদান করা হয়েছে) নিশ্চিত",
        repaymentConfirmation: "মুক্তি নিশ্চিত",
        cancellationPayment: "প্রতিদান নিশ্চিত করা বাতিল করুন",
        CancelPayment: "আপনি কি নিশ্চিত আপনি বাতিল করতে চান?",
        manualConfirmPayment: "লোন বিতরণ নিশ্চিত করুন",
        manualConfirmPaymentConfirmation: "আপনি কি নিশ্চিতভাবে বিভ্রান্ত নিশ্চিত করুন?",
        expeditedPayment: "Is it urgent",
        expeditedPaymentConfirmation: "আপনি কি নিশ্চিত তাড়াতাড়ি করতে চান?",
        deletion: "মুছে ফেলুন",
        confirmDeletion: "মুছে ফেলার কথা নিশ্চিত?",
        regainAccount: "পুনরুদ্ধার Wallet",
        confirmRegainAccount: "পুনরুদ্ধার করতে নিশ্চিত?",
        paymentSuccessRecord: "একটি সফল প্রতিদান রেকর্ড আছে, অনুগ্রহ করে প্রয়োজনীয় পরিশোধ সিরিয়াল নাম্বার টিক্সিদে পূরণ করুন",
        retry: "আবার জানাও",
        retryConfirmation: "আপনি কি নিশ্চিত যে আপনি আবার জানাতে চান?",
        timePrompt: "সংগ্রহের সময় বর্তমান সময়ের চেয়ে পরে থাকতে পারে না!",
        debitCard: "প্রক্সি প্রতিদান কার্ড",
        bankCard: "ব্যাংক কার্ড",
        manualValidation: "নিয়মিত নিশ্চিত স্বাভাবিক",
        confirmationIsNormal: "SMS বার্তা সংগ্রহের মাধ্যমে স্বাভাবিক হিসেবে নিশ্চিত",
        modifyChannel:"চ্যানেল সম্পাদনা করুন",
        collectionConfirmation: "সংগ্রহ করা অ্যাকাউন্ট নাম্বার",
        updateNotice: "ব্যবসায়ীর ঘোষণা পরিবর্তন করুন",
        designated: "Designed Merchant Notifyation",
        switchgearNotice: "স্বাভাবিক।",
        individualHouseholdCollection: "সংগ্রহের তথ্য আমদানি করুন"
    }
};
//导出按钮
const translations = {
    'en': {
        'replacePay': 'Import of pending payments',
        'exportPrePay': 'Exporting data to be transferred',
        'importResult': 'Importing transfer results',
        'exportRecord': 'Exporting payment records',
        'retryBatch': 'Batch notification',
        'expeditedBatch': 'Batch urgent',
        'export': 'export',
        'addWallet': 'Add Wallet',
        'newChannels': 'New channels',
        'withdrawFunds': 'withdraw funds',
        'newMerchantsAdded': 'New Merchants',
        'addCollectionBankCard': 'New collection bank card',
        'editCollectionBankCard': 'Edit and collect bank cards',
        "addNotice": "New Merchant Announcement",
        "agentPay": "Import the agent account data",
        "addCollectionInformation": "Add collection information",
        "acceptance": "Import the individual account acceptance collection data",
        "individualHouseholdCollection": "Import the individual account payment collection data",
    },
    'zh': {
        'replacePay': '导入待付数据',
        'exportPrePay': '导出待转账数据',
        'importResult': '导入转账结果',
        'exportRecord': '导出付款记录',
        'retryBatch': '批量通知',
        'expeditedBatch': '批量加急',
        'export': '导出',
        'addWallet': '新增钱包',
        'newChannels': '新增渠道',
        'newMerchantsAdded': '新增商户',
        'withdrawFunds': '提现',
        'addCollectionBankCard': '新增归集银行卡',
        'editCollectionBankCard': '编辑归集银行卡',
        "addNotice": "新增商户公告",
        "agentPay": "导入代理户数据",
        "addCollectionInformation": "新增归集信息",
        "acceptance": "导入个户承兑归集数据",
        "individualHouseholdCollection": "导入个户代付归集数据",
    },
    'ban': {
        'replacePay': 'প্রতিদানের তথ্য ইম্পোর্ট করুন',
        'exportPrePay': 'ট্রান্সফার্নারের তথ্য প্রাপ্ত হওয়ার অপেক্ষায় রপ্তানি করো',
        'importResult': 'পরিবর্তনের ফলাফল ইম্পোর্ট করুন',
        'exportRecord': 'প্রতিদান রেকর্ড রপ্তানি করো',
        'retryBatch': 'ব্যাচ ঘোষণা',
        'expeditedBatch': 'ত্বরান্বিত পরিমাণ',
        'export': 'এক্সপোর্ট করো',
        'addWallet': 'ওয়ালেট যোগ করো',
        'newChannels': 'নতুন চ্যানেল যোগ করো',
        'withdrawFunds': 'আবহাওয়া',
        'newMerchantsAdded': 'নতুন ব্যবসায়ী যোগ করো',
        'addCollectionBankCard': 'সংগ্রহ ব্যাংক কার্ড যোগ করো',
        'editCollectionBankCard': 'ব্যাংক কার্ড সম্পাদনা ও সংগ্রহ করো',
        "addNotice": "New Merchant Announcement",
        "agentPay": "এজেন্ট ডেটা আমদানি করুন",
        "addCollectionInformation": "সংগ্রহের তথ্য যোগ করুন",
        "acceptance": "সংগ্রহের তথ্য আমদানি করুন",
        "individualHouseholdCollection": "ব্যক্তিগত পেমেন্ট সংগ্রহের তথ্য আমদানি করুন",
    }
};



// ----------------------------------------列表国际化-------------------------------------------------
//渠道管理
const channel = {
    'en': {
        'id': 'Serial No',
        'channelName': 'Channel Name',
        'groupId': 'Group ID',
        'replaceCollectStatus': 'collector status',
        'replacePayStatus': 'escrow status',
        'businessType': 'Business Type',
        'replacePayProductType': 'Payment product type',
        'collectionProductType': 'Type of collection product',
        'businessCountry': 'our country',
        'right': 'manipulate',
        "freezingOfCollections": "Freezing of collections",
        "freezePaymentBehalf": "Freeze Payment on Behalf",
        "handlingFeeFixed": "Handling fee - fixed",
        "handlingFeeConditions": "Handling Fee - Conditions"
    },
    'zh': {
        'id': '序号',
        'channelName': '渠道名称',
        'groupId': '群组ID',
        'replaceCollectStatus': '代收状态',
        'replacePayStatus': '代付状态',
        'businessType': '业务类型',
        'replacePayProductType': '代付产品类型',
        'collectionProductType': '代收产品类型',
        'businessCountry': '国家',
        'right': '操作',
        "freezingOfCollections": "冻结代收",
        "freezePaymentBehalf": "冻结代付",
        "handlingFeeFixed": "手续费-固定",
        "handlingFeeConditions": "手续费-条件"
    },
    'ban': {
        'id': 'সংখ্যা',
        'channelName': 'চ্যানেলের নাম',
        'groupId': 'গ্রুপ ID',
        'replaceCollectStatus': 'সংগ্রহের অবস্থা',
        'replacePayStatus': 'প্রদানের অবস্থা',
        'businessType': 'ব্যবসার ধরন',
        'replacePayProductType': 'পুরস্কার প্রযুক্তির ধরন',
        'collectionProductType': 'পণ্য ধরনের সংগ্রহ',
        'businessCountry': 'দেশ',
        'right': 'অপারেশন',
        "freezingOfCollections": "ফ্রিজ সংগ্রহ",
        "freezePaymentBehalf": "অন্যদের পক্ষ থেকে মুক্তি প্রদান করুন",
        "handlingFeeFixed": "হ্যান্ডিং ফি - ঠিক করা হয়েছে",
        "handlingFeeConditions": "হ্যান্ডিং ফিস - অবস্থা"
    }
};
//商户管理
const merchant = {
    'en': {
        'id': 'Serial No',
        'merchantCode': 'Merchant ID',
        'merchantName': 'merchant name',
        'status': 'Merchant Status',
        'enableAmount': 'Available balance',
        'freeseAmount': 'Frozen balance',
        'amount': 'Overall balance',
        'workField': 'sector',
        'businessCountry': 'Country of operation',
        'createTime': 'Creation time',
        'right': 'manipulate',
        'edit': 'modifications',
        'auditOperation': 'Audit operation',
        'Withdrawal': 'Withdrawal application',
        'manualConfirmPayment': 'Manually confirm the loan',
        'payProducts': 'Proxy payment channel',
        'collectionProducts': 'Collection channel',
        'payStatus': 'Proxy payment status',
        'collectionStatus': 'Collection status',
    },
    'zh': {
        'id': '序号',
        'merchantCode': '商户ID',
        'merchantName': '商户名称',
        'status': '商户状态',
        'enableAmount': '可用余额',
        'freeseAmount': '冻结余额',
        'amount': '总余额',
        'workField': '行业',
        'businessCountry': '业务所在国家',
        'createTime': '创建时间',
        'right': '操作',
        'edit': '修改',
        'auditOperation': '审核操作',
        'Withdrawal': '提现申请',
        'manualConfirmPayment': '人工确认放款',
        'payProducts': '代付通道',
        'collectionProducts': '代收通道',
        'payStatus': '代付状态',
        'collectionStatus': '代收状态',
    },
    'ban': {
        'id': 'সংখ্যা',
        'merchantCode': 'বার্তা ID',
        'merchantName': 'মার্স্যান্ট নাম',
        'status': 'স্ট্যাটাস',
        'enableAmount': 'বিদ্যমান ব্যবস্থা',
        'freeseAmount': 'ফ্রেস বাজার',
        'amount': 'সম্পূর্ণ মানসমূহ',
        'workField': 'শিল্প',
        'businessCountry': 'ব্যবসা দেশ',
        'createTime': 'সৃষ্টির সময়',
        'right': 'অপারেশন',
        'edit': 'পরিবর্তন করুন',
        'auditOperation': 'Audit অপারেশন',
        'Withdrawal': 'অ্যাপলিকেশন বাতিল করো',
        'manualConfirmPayment': 'লোন বিতরণ নিশ্চিত করুন',
        'payProducts': 'পুরষ্কার চ্যানেল',
        'collectionProducts': 'সংগ্রহ চ্যানেল',
        'payStatus': 'প্রদানের অবস্থা',
        'collectionStatus': 'সংগ্রহের অবস্থা',
    }
};
//商户账户管理
const account = {
    'en': {
        'id': 'Serial No',
        'merchantCode': 'Merchant ID',
        'merchantName': 'merchant name',
        'channelCode': 'Channel',
        'collectionStatus': 'collector status',
        'payStatus': 'escrow status',
        'openAccountStatus': 'Account Status',
        'right': 'manipulate',
        'operatingBalance': 'Operating balance',
        'commissionEditing': 'Handling Fee Editor',
        'amount': 'sum of money',
        'operationType': 'Operation Type',
        'auditStatus': 'Audit Status',
        'remark': 'remark',
        'operator': 'operator',
        'operatingTime': 'operating time',
    },
    'zh': {
        'id': '序号',
        'merchantCode': '商户ID',
        'merchantName': '商户名称',
        'channelCode': '所属渠道',
        'collectionStatus': '代收状态',
        'payStatus': '代付状态',
        'openAccountStatus': '开户状态',
        'right': '操作',
        'operatingBalance': '操作余额',
        'commissionEditing': '手续费编辑',
        'amount': '金额',
        'operationType': '操作类型',
        'auditStatus': '审核状态',
        'remark': '备注',
        'operator': '操作人',
        'operatingTime': '操作时间',
    },
    'ban': {
        'id': 'সংখ্যা',
        'merchantCode': 'বার্তা ID',
        'merchantName': 'মার্স্যান্ট নাম',
        'channelCode': 'চ্যানেল',
        'collectionStatus': 'সংগ্রহের অবস্থা',
        'payStatus': 'পপ্রদানের অবস্থা',
        'openAccountStatus': 'অ্যাকাউন্ট খোলার অবস্থা',
        'right': 'অপারেশন',
        'operatingBalance': 'অপারেশনের মানসমূহ',
        'commissionEditing': 'হ্যান্ডিং ফি সম্পাদক',
        'amount': 'অর্থের পরিমাণ',
        'operationType': 'অপারেশনের ধরন',
        'auditStatus': 'প্রাকদর্শন অবস্থা',
        'remark': 'মন্তব্য',
        'operator': 'অপারেটর',
        'operatingTime': 'অপারেশনের সময়',
    }
};
//代收管理
const collection = {
    'en': {
        'collectionBillNo': 'Receipt number (not duplicated)',
        'merchantCode': 'Receipt number (not duplicated)',
        'merchantName': 'Merchant name',
        'appID': 'App ID',
        'merchantOrderNo': 'Merchant Order No.',
        'custName': 'Customer Name',
        'custPhone': 'Customer Cell Phone Number',
        'custAccount': 'Customer Account',
        'requestAmount': 'Amount requested',
        'actualAmount': 'Actual amount received',
        'payExpireTime': 'Payment expiration time',
        'fee': 'Payment of renewal fee',
        'walletSerialNo': 'Payment Runner Txid',
        'experience': 'Payment Channels',
        'paymentCard': 'Payment Card No.',
        'requestTime': 'Timing requests for collection',
        'dealTime': 'Successful receipt time',
        'status': 'collection status',
        'remark': 'remark',
        'right': 'manipulate',
        'humanMatching': 'human matching',
        'importantNotice': 're-notification',
        'colletionChannel': 'Collection channels',
        'collectionWalletNo': 'Receiving wallet number',
        'collectionProductType': 'Product type',
        'tradeNo': 'Platform flow number(Collection number)',
        'merchantSerialNo': 'merchant flow number',
        'callBack': 'notification status',
        'flow': 'Replacement of running water',
        'viewVoucher': 'View certificate',
        'openLinkTime': 'Open checkout time',
        'submitLinkTime': 'Submit checkout time',
        'callBackTime': 'Callback success time',
    },
    'zh': {
        'collectionBillNo': '收款单号(商户定义、不重复)',
        'merchantCode': '商户编号',
        'merchantName': '商户名称',
        'appID': '应用ID',
        'merchantOrderNo': '商户订单号',
        'custName': '客户姓名',
        'custPhone': '客户手机号',
        'custAccount': '客户账号',
        'requestAmount': '请求收款金额',
        'actualAmount': '实际收款金额',
        'payExpireTime': '支付过期时间',
        'fee': '支付收续费',
        'walletSerialNo': '支付流水号Txid',
        'experience': '支付渠道',
        'paymentCard': '支付卡号',
        'requestTime': '请求收款时间',
        'dealTime': '收款成功时间',
        'status': '收款状态',
        'remark': '备注',
        'right': '操作',
        'humanMatching': '人工匹配',
        'importantNotice': '重新通知',
        'colletionChannel': '收款渠道',
        'collectionWalletNo': '收款钱包编号',
        'collectionProductType': '产品类型',
        'tradeNo': '平台流水号(代收单号)',
        'merchantSerialNo': '商户流水号',
        'callBack': '通知状态',
        'flow': '补录流水',
        // 'viewVoucher': '查看凭证',
        'viewVoucher': 'View certificate',
        'openLinkTime': '打开收银台时间',
        'submitLinkTime': '提交收银台时间',
        'callBackTime': '回调成功时间',
    },
    'ban': {
        'collectionBillNo': 'নাম্বার গ্রহণ করুন (ব্যবসায়ীর নির্ধারিত এবং দুই বিন্যাস নয়)',
        'merchantCode': 'বার্তা ID',
        'merchantName': 'মার্স্যান্ট নাম',
        'appID': 'অ্যাপলিকেশন ID',
        'merchantOrderNo': 'মার্স্টিং অর্ডার নাম্বার',
        'custName': 'স্বনির্বাচিত নাম',
        'custPhone': 'স্বনির্বাচিত ফোন নাম্বার',
        'custAccount': 'স্বনির্বাচিত অ্যাকাউন্ট',
        'requestAmount': 'পরিমাণের অনুরোধ',
        'actualAmount': 'প্রকৃত পরিমাণ পেয়েছে',
        'payExpireTime': 'পুরষ্কার মেয়াদের সময়',
        'fee': 'টাকা এবং পুনরুদ্ধার ফিস',
        'walletSerialNo': 'প্রতিদান সিরিয়াল সংখ্যা Txid',
        'experience': 'পুরষ্কার চ্যানেল',
        'paymentCard': 'প্রদান করা কার্ড নাম্বার',
        'requestTime': 'অনুরোধ করার সময়',
        'dealTime': 'সফল সময়',
        'status': 'প্রদানের অবস্থা',
        'remark': 'মন্তব্য',
        'right': 'অপারেশন',
        'humanMatching': 'হ্যান্ডাল মিল',
        'importantNotice': 'আবার জানাও',
        'colletionChannel': 'Payment channel',
        'collectionWalletNo': 'প্রতিদানের ওয়ালেট নম্বর',
        'collectionProductType': 'পণ্যের ধরন',
        'tradeNo': 'প্ল্যাটফর্ম সিরিয়াল সংখ্যা(সংগ্রহের সংখ্যা)',
        'merchantSerialNo': 'সিরিয়াল সংখ্যা',
        'callBack': 'বার্তা',
        'flow': 'অতিরিক্ত তথ্য রেকর্ড করুন',
        'viewVoucher': 'View certificate',
        // 'viewVoucher': 'অনুগ্রহ প্রদর্শন',
        'openLinkTime': 'পরীক্ষার সময় খোলো',
        'submitLinkTime': 'পরীক্ষার সময় বার্তা করুন',
        'callBackTime': 'সফলভাবে ফোল্ডারের সময়',
    }
};
//付款记录
const  another ={
    'en': {
        'replacePayBillNo': 'Payment order number (platform running number)',
        'merchantSerialNo': 'merchant flow number',
        'merchantCode': 'Merchant ID',
        'merchantName': 'Merchant name',
        'applicationID': 'application ID',
        'merchantOrderNo': 'Merchant Order Number',
        'custName': 'Customer Name',
        'custPhone': 'Customer Cell Phone Number',
        'custAccount': 'Customer Account Number',
        'dealTime': 'Payment success time',
        'status': 'payment status',
        'walletSerialNo': 'Payment Runner Txid',
        'remark': 'remark',
        'right': 'manipulate',
        'payAmount': 'Amount of payment',
        'payFee': 'Payment of Handling Fee',
        'payChannel': 'Payment Payment Channels',
        'payWalletNo': 'Payment wallet number',
        'payProductType': 'Product type',
        'merchantRequestTime': 'Time of request for payment',
        'walletRequestTime': 'Script requests payment time',
        'callBack': 'Notification status',
        'callBackTime': 'Callback success time',
    },
    'zh': {
        'replacePayBillNo': '付款单号(平台流水号)',
        'merchantSerialNo': '商户流水号',
        'merchantCode': '商户编号',
        'merchantName': '商户名称',
        'applicationID': '应用ID',
        'merchantOrderNo': '商户订单号',
        'custName': '客户姓名',
        'custPhone': '客户手机号',
        'custAccount': '客户账号',
        'dealTime': '付款成功时间',
        'status': '付款状态',
        'walletSerialNo': '支付流水号Txid',
        'remark': '备注',
        'right': '操作',
        'payAmount': '付款金额',
        'payFee': '支付手续费',
        'payChannel': '支付渠道',
        'payWalletNo': '支付钱包编号',
        'payProductType': '产品类型',
        'merchantRequestTime': '请求付款时间',
        'walletRequestTime': '脚本请求付款时间',
        'callBack': '通知状态',
        'callBackTime': '回调成功时间',
    },
    'ban': {
        'replacePayBillNo': 'প্রতিষ্ঠান সংখ্যা (প্ল্যাটফর্ম সিরিয়াল সংখ্যা)',
        'merchantSerialNo': 'সিরিয়াল সংখ্যা',
        'merchantCode': 'বার্তা ID',
        'merchantName': 'মার্স্যান্ট নাম',
        'applicationID': 'অ্যাপলিকেশন ID',
        'merchantOrderNo': 'মার্স্টিং অর্ডার নাম্বার',
        'custName': 'স্বনির্বাচিত নাম',
        'custPhone': 'স্বনির্বাচিত ফোন নাম্বার',
        'custAccount': 'স্বনির্বাচিত অ্যাকাউন্ট',
        'dealTime': 'সফল সময়',
        'status': 'পপ্রদানের অবস্থা',
        'walletSerialNo': 'প্রতিদান সিরিয়াল সংখ্যা Txid',
        'remark': 'মন্তব্য',
        'right': 'অপারেশন',
        'payAmount': 'প্রদানের পরিমাণ',
        'payFee': 'টাকা হ্যান্ডিং ফি',
        'payChannel': 'পুরষ্কার চ্যানেল',
        'payWalletNo': 'প্রতিদানের ওয়ালেট নাম্বার',
        'payProductType': 'পণ্যের ধরন',
        'merchantRequestTime': 'অনুরোধ করার সময়',
        'walletRequestTime': 'স্ক্রিপ্টের প্রতিদানের সময় অনুরোধ করে',
        'callBack': 'বার্তা',
        'callBackTime': 'সফলভাবে ফোল্ডারের সময়',
    }
}
//钱包流水记录
const walletFlow={
    'en': {
        'replacePayBillNo': 'Payment order number | Platform serial number',
        'walletSerialNo': 'Wallet serial number',
        'payWalletNo': 'Payment wallet number',
        'behalfAmount': 'Wallet balance',
        'payAmount': 'Payment amount',
        'payAmountTotal': 'Total amount of actual payment',
        'status': 'status',
        'dealTime': 'Transaction closing time',
        'failure': 'Cause of failure',
        'payFee': 'Pay commission',
        'payChannel': 'Payment channel',
        'soriginalData': 'Original analytic flow',
        'verificationStatus': 'Storage status',
        'warehouseType': 'Storage method',
        'updateTime': 'Update time',
        'createTime': 'Creation time',
    },
    'zh': {
        'replacePayBillNo': '付款单号|平台流水号',
        'walletSerialNo': '钱包流水号',
        'payWalletNo': '支付钱包编号',
        'behalfAmount': '钱包余额',
        'payAmount': '付款金额',
        'payAmountTotal': '实际付款总金额',
        'status': '状态',
        'dealTime': '交易完成时间',
        'failure': '失败原因',
        'payFee': '支付手续费',
        'payChannel': '支付渠道',
        'soriginalData': '原始解析流水',
        'verificationStatus': '入库状态',
        'warehouseType': '入库方式',
        'updateTime': '更新时间',
        'createTime': '创建时间',
    },
    'ban': {
        'replacePayBillNo': 'প্ল্যাটফর্ম সিরিয়াল সংখ্যা',
        'walletSerialNo': 'ওয়ালেট সিরিয়াল নাম্বার',
        'payWalletNo': 'প্রতিদানের ওয়ালেট নাম্বার',
        'behalfAmount': 'ওয়ালেটের মানসমূহ',
        'payAmount': 'প্রদানের পরিমাণ',
        'payAmountTotal': 'প্রকৃত মোট পুরস্কারের পরিমাণ',
        'status': 'অবস্থা',
        'dealTime': 'ট্রান্সফেন্স পূর্ণ সময়',
        'failure': 'ব্যর্থতার কারণ',
        'payFee': 'টাকা হ্যান্ডিং ফি',
        'payChannel': 'পুরষ্কার চ্যানেল',
        'soriginalData': 'প্রাথমিক বিশ্লেষণের প্রবাহ',
        'verificationStatus': 'সংরক্ষণের অবস্থা',
        'warehouseType': 'ভাণ্ডার পদ্ধতি',
        'updateTime': 'সময় আপডেট করো',
        'createTime': 'সৃষ্টির সময়',
    }
}
//资金流水
const  capital ={
    'en': {
        'id': 'Serial No',
        'merchantCode': 'Merchant Number',
        'applicationID': 'Application ID',
        'tradeNo': 'merchant flow number',
        'walletSerialNo': 'Payment Runner Txid',
        'businessType': 'Business Type',
        'status': 'status',
        'experience': 'Transaction type',
        'paymentChannels': 'Payment Channels',
        'orderAmount': 'Order Amount',
        'incomeAmount': 'Amount credited',
        'fee': 'handling fee',
        'actualReceivedAmount': 'Actual received amount',
        'channelFee': 'channel cost',
        'enableAmountBefore': 'Available balance before change',
        'enableAmountAfter': 'Available balance after changes',
        'enableAmountChange': 'Change in available balance',
        'settleTime': 'settlement time',
        'dealTime': 'trading hours',
        'createTime': 'Creation time',

    },
    'zh': {
        'id': '序号',
        'merchantCode': '商户编号',
        'applicationID': '应用ID',
        'tradeNo': '商户流水号',
        'walletSerialNo': '支付流水号Txid',
        'businessType': '业务类型',
        'status': '状态',
        'experience': '交易类型',
        'paymentChannels': '支付渠道',
        'orderAmount': '订单金额',
        'incomeAmount': '入账金额',
        'fee': '手续费',
        'actualReceivedAmount': '实际收款金额',
        'channelFee': '渠道成本',
        'enableAmountBefore': '变动前可用余额',
        'enableAmountAfter': '变动后可用余额',
        'enableAmountChange': '可用余额变动数目',
        'settleTime': '结算时间',
        'dealTime': '交易时间',
        'createTime': '创建时间',

    },
    'ban': {
        'id': 'সংখ্যা',
        'merchantCode': 'বার্তা ID',
        'applicationID': 'অ্যাপলিকেশন ID',
        'tradeNo': 'সিরিয়াল সংখ্যা',
        'walletSerialNo': 'প্রতিদান সিরিয়াল সংখ্যা Txid',
        'businessType': 'ব্যবসার ধরন',
        'status': 'অবস্থা',
        'experience': 'ট্রান্সফিকেশন ধরন',
        'paymentChannels': 'পুরষ্কার চ্যানেল',
        'orderAmount': 'পরিমাণ',
        'incomeAmount': 'প্রবেশের পরিমাণ',
        'fee': 'সার্ভিস চার্জ',
        'actualReceivedAmount': 'প্রকৃত পরিমাণ',
        'channelFee': 'চ্যানেলের খরচ',
        'enableAmountBefore': 'পরিবর্তনের পূর্বে উপস্থিত ব্যবস্থা',
        'enableAmountAfter': 'পরিবর্তনের পর উপস্থিত ব্যবস্থা',
        'enableAmountChange': 'বিদ্যমান ব্যালেন্স পরিবর্তনের সংখ্যা',
        'settleTime': 'বৈশিষ্ট্যাবলীর সময়',
        'dealTime': 'ট্রান্ডিং সময়',
        'createTime': 'সৃষ্টির সময়'
    }
}
//电子钱包
const  purses ={
    'en': {
        'accountPhone': 'Wallet number',
        'deivceName': 'Device name',
        'cardType': 'Wallet classification',
        'cloudStatus': 'Cloud machine status',
        'walletType': 'Wallet type',
        'behalfAmount': 'Wallet Balance',
        'accountNo': 'account number',
        'accountName': 'account name',
        'openBankCode': 'Bank code',
        'openBankName': 'Name of Bank',
        'operType': 'typology',
        'status': 'wallet state',
        'remark': 'Disabling reason',
        'createTime': 'Creation time',
        'applictionId': 'Device name - Application ID',
        'deivceCode': 'Device number',
        'walletPin': 'Wallet PIN code',
        'deivcePosition': 'Equipment Location',

        'openType': 'open type',
        'deivceType': 'Device Type',

        'collectionDayLimitCount': 'Daily collection limit',
        'collectionDayLimitAmount': 'Daily collection quota',
        'collectionDayLeftCount': 'Daily collection of remaining transactions',
        'collectionDayLeftAmount': 'Daily collection of remaining credit limit',
        'moveAmount': 'transferred amount',
        'collectionMonthLimitAmount': 'Monthly collection limit',
        'collectionMonthLimitCount': 'Monthly collection limit',
        'collectionMonthLeftCount': 'Remaining number of monthly collection transactions',
        'collectionMonthLeftAmount': 'Remaining monthly collection quota',

        'payDayLimitAmount': 'Daily payment limit',
        'payDayLeftAmount': 'Daily payment with remaining balance',
        'payDayLeftCount': 'Remaining number of daily proxy payments',
        'payDayLimitCount': 'Daily payment limit',
        'payMonthLeftAmount': 'Monthly payment with remaining balance',
        'payMonthLeftCount': 'Remaining monthly payments on behalf of others',
        'payMonthLimitAmount': 'Monthly payment limit',
        'payMonthLimitCount': 'Monthly payment limit',

        'right': 'manipulate',
        "channelCode": "Channel ID",
    },
    'zh': {
        'accountPhone': '钱包编号',
        'deivceName': '设备名称',
        'cardType': '钱包分类',
        'walletType': '钱包类型',
        'cloudStatus': '云机状态',
        'behalfAmount': '钱包余额',
        'accountNo': '账户号',
        'accountName': '账户名',
        'openBankCode': '开户行code',
        'openBankName': '开户行名称',
        'operType': '类型',
        'status': '钱包状态',
        'remark': '禁用原因',
        'applictionId': '设备名-应用ID',
        'deivceCode': '设备编号',
        'walletPin': '钱包PIN码',
        'deivcePosition': '设备位置',
        'createTime': '创建时间',
        'openType': '打开类型',
        'deivceType': '设备类型',
        "channelCode": "渠道ID",

        'collectionDayLimitCount': '日代收笔数限制',
        'collectionDayLimitAmount': '日代收额度',
        'collectionDayLeftCount': '日代收剩余笔数',
        'collectionDayLeftAmount': '日代收剩余额度',
        'moveAmount': '转移额度',
        'collectionMonthLimitAmount': '月代收限额',
        'collectionMonthLimitCount': '月代收笔数限制',
        'collectionMonthLeftCount': '月代收剩余笔数',
        'collectionMonthLeftAmount': '月代收剩余额度',

        'payDayLimitAmount': '日代付额度',
        'payDayLeftAmount': '日代付剩余额度',
        'payDayLeftCount': '日代付剩余笔数',
        'payDayLimitCount': '日代付笔数限制',
        'payMonthLeftAmount': '月代付剩余额度',
        'payMonthLeftCount': '月代付剩余笔数',
        'payMonthLimitAmount': '月代付额度',
        'payMonthLimitCount': '月代付笔数限制',

        'right': '操作',
    },
    'ban': {
        'accountPhone': 'ওয়ালেট নাম্বার',
        'deivceName': 'Equipment নাম',
        'cardType': 'ওয়ালেট শ্রেণীকরণ',
        'walletType': 'ওয়ালেটের ধরন',
        'cloudStatus': 'ক্লাউডের অবস্থা',
        'behalfAmount': 'ওয়ালেটের মানসমূহ',
        'accountNo': 'অ্যাকাউন্ট নাম্বার',
        'accountName': 'অ্যাকাউন্টের নাম',
        'openBankCode': 'ব্যাংক কোড খোলা অ্যাকাউন্ট',
        'openBankName': 'ব্যাংকের নাম খোলা অ্যাকাউন্ট',
        'operType': 'ধরন',
        'status': 'ওয়ালেটের অবস্থা',
        'remark': 'নিষ্ক্রিয় করার কারণ',
        'createTime': 'সৃষ্টির সময়',
        'applictionId': 'ডিভাইসের নাম - অ্যাপলিকেশন ID',
        'deivceCode': 'Equipment number',
        'walletPin': 'মালিকের পিন কোড',
        'deivcePosition': 'Equipment অবস্থান',
        'openType': 'ধরন খোলো',
        'deivceType': 'Equipment type',

        'collectionDayLimitCount': 'প্রতিদিন সংগ্রহের সীমা',
        'collectionDayLimitAmount': 'প্রতিদিন সংগ্রহের উদ্ধৃতি',
        'collectionDayLeftCount': 'প্রতিদিন সংগ্রহের সংখ্যা বাকি আছে',
        'collectionDayLeftAmount': 'বাকি ক্রেডিট সীমানার প্রতিদিন সংগ্রহ',
        'moveAmount': 'স্থানান্তর করো',
        'collectionMonthLimitAmount': 'মাসিক সংগ্রহ সীমা',
        'collectionMonthLimitCount': 'মাসিক সংগ্রহ সীমা',
        'collectionMonthLeftCount': 'মাসিক সংগ্রহের সংখ্যার বাকি আছে',
        'collectionMonthLeftAmount': 'মাসিক সংগ্রহের উদ্ধৃতি',

        'payDayLimitAmount': 'প্রতিদিন পুরস্কার সীমা',
        'payDayLeftAmount': 'বাকি বর্তমান ব্যালেনের সাথে প্রতিদিন পুরস্কার',
        'payDayLeftCount': 'প্রতিদিন প্রক্সি প্রদানের সংখ্যা বাকি আছে',
        'payDayLimitCount': 'প্রতিদিন পুরস্কার সীমা',
        'payMonthLeftAmount': 'মাসিক পুরস্কার বাকি ব্যালেন্স দিয়ে',
        'payMonthLeftCount': 'অন্যদের পক্ষ থেকে মাসিক টাকা রাখবে',
        'payMonthLimitAmount': 'মাসিক পুরস্কার সীমা',
        'payMonthLimitCount': 'মাসিক পুরস্কার সীমা',
        "channelCode": "চ্যানেল ID",
        'right': 'অপারেশন',
    }
}
//钱包流水记录
const  wallet ={
    'en': {
        'payWalletNo': 'Payment Wallet No',
        'walletSerialNo': 'Transaction serial number',
        'deivceCode': 'Device number',
        'actualAmount': 'Actual amount received',
        'createTime': 'Storage time',
        'payFee': 'handling fee',
        'custphone': 'Customer mobile phone number',
        'status': 'state of affairs',
        'verificationStatus': 'in-stock status',
        'walletType': 'Types of e-wallets',
        'warehouseType': 'Incoming type',
        'dealTime': 'Transaction completion time',
        'dealTimeStart': 'Transaction completion start time',
        'dealTimeEnd': 'Transaction completion end time',
        'soriginalData': 'Original analytic flow',
    },
    'zh': {
        'payWalletNo': '支付钱包编号',
        'walletSerialNo': '交易流水号',
        'deivceCode': '设备编号',
        'actualAmount': '实际收款金额',
        'createTime': '入库时间',
        'payFee': '手续费',
        'custphone': '客户手机号',
        'status': '状态',
        'verificationStatus': '入库状态',
        'walletType': '电子钱包类型',
        'warehouseType': '入库类型',
        'dealTime': '交易完成时间',
        'dealTimeStart': '交易完成开始时间',
        'dealTimeEnd': '交易完成结束时间',
        'soriginalData': '原始解析流水',
    },
    'ban': {
        'payWalletNo': 'প্রতিদানের ওয়ালেট নাম্বার',
        'walletSerialNo': 'Transaction serial number',
        'deivceCode': 'Equipment number',
        'actualAmount': 'প্রকৃত পরিমাণ পেয়েছে',
        'createTime': 'সংরক্ষণের সময়',
        'payFee': 'সার্ভিস চার্জ',
        'custphone': 'স্বনির্বাচিত মোবাইল ফোন নাম্বার',
        'status': 'অবস্থা',
        'verificationStatus': 'সংরক্ষণের অবস্থা',
        'walletType': 'ইলেকট্রনিক ওয়ালেটের ধরন',
        'warehouseType': 'Storage type',
        'dealTime': 'ট্রান্সফেন্স পূর্ণ সময়',
        'dealTimeStart': 'ট্রান্সফেন্স শুরু করার সময়',
        'dealTimeEnd': 'ট্রান্সপ্রেশন সমাপ্তির সময় শেষ',
        'soriginalData': 'প্রাথমিক বিশ্লেষণের প্রবাহ',
    }
}

//归集银行卡信息
const  banCard ={
    'en': {
        'accountPhone': 'Wallet number',
        'operType': 'type',
        'status': 'status',
        'walletPin': 'Wallet PIN code',
        'cardType': 'Bank card/e-wallet category',
        'walletType': 'E-wallet type',
        'accountName': 'Account name',
        'accountNo': 'Account number',
        'openBankName': 'Account bank name',
        'openBankCode': 'Account bank code',
        'channelCode': 'Channel ID',
        'collectionDayFreezeAmount': 'Frozen amount',
        'collectionDayLeftAmount': 'Daily transfer of the remaining amount',
        'collectionDayLimitAmount': 'Daily transfer limit',
        'deivceCode': 'Equipment number',
        'deivcePosition': 'Device location',
        'createTime': 'Creation date',
        'right': 'manipulate',

    },
    'zh': {
        'accountPhone': '钱包编号',
        'operType': '类型',
        'status': '状态',
        'walletPin': '钱包PIN码',
        'cardType': '银行卡/电子钱包分类',
        'walletType': '电子钱包类型',
        'accountName': '账户名',
        'accountNo': '账户号',
        'openBankName': '开户行名称',
        'openBankCode': '开户行code',
        'channelCode': '渠道ID',
        'collectionDayFreezeAmount': '冻结金额',
        'collectionDayLeftAmount': '日转入剩余额度',
        'collectionDayLimitAmount': '日转入限额',
        'deivceCode': '设备编号',
        'deivcePosition': '设备位置',
        'createTime': '创建日期',
        'right': '操作',
    },
    'ban': {
        'accountPhone': 'ওয়ালেট নাম্বার',
        'operType': 'ধরন',
        'status': 'অবস্থা',
        'walletPin': 'ওয়ালেট PIN কোড',
        'cardType': 'ব্যাংক কার্ড/ইলেক্ট্রোনিক ওয়ালেটের ক্লাসিশন',
        'walletType': 'ইলেকট্রনিক ওয়ালেটের ধরন',
        'accountName': 'অ্যাকাউন্টের নাম',
        'accountNo': 'অ্যাকাউন্ট নাম্বার',
        'openBankName': 'ব্যাংকের নাম খোলা অ্যাকাউন্ট',
        'openBankCode': 'ব্যাংক কোড খোলা অ্যাকাউন্ট',
        'channelCode': 'চ্যানেল ID',
        'collectionDayFreezeAmount': 'ফ্রিসের পরিমাণ',
        'collectionDayLeftAmount': 'বাকি ক্রেডিট সীমানার প্রতিদিন পরিবর্তন',
        'collectionDayLimitAmount': 'প্রতিদিন পরিবর্তন সীমা',
        'deivceCode': 'Equipment number',
        'deivcePosition': 'Equipment অবস্থান',
        'createTime': 'সৃষ্টির তারিখ',
        'right': 'অপারেশন',
    }
}

//归集明细信息
const  detailed ={
    'en': {
        'accountNoTo': 'The collected account number',
        'replacePayBillNo': 'Collect platform serial number',
        'payWalletNo': 'Payment wallet number',
        'walletType': 'Collection wallet type',
        'status': 'status',
        'payAmount': 'Payment amount',
        'balanceCardType': 'Need to collect the card type',
        'balanceCardToType': 'Collects to card type',
        'merchantRequestTime': 'Time when the collection is initiated',
        'dealTime': 'Collection success time',
        'walletRequestTime': 'Script request time',
        'remark': 'remark',
        'createTime': 'Creation time',
        'right': 'manipulate',
        'deivceCode': 'Equipment number',
        'batchNo': 'Batch number',
        'cloudStatus': 'Collection method',
    },
    'zh': {
        'accountNoTo': '归集到的账户号',
        'replacePayBillNo': '归集平台流水号',
        'payWalletNo': '支付钱包编号',
        'walletType': '归集钱包类型',
        'status': '状态',
        'payAmount': '付款金额',
        'balanceCardType': '需要归集卡类型',
        'balanceCardToType': '归集到卡类型',
        'merchantRequestTime': '发起归集时间',
        'walletRequestTime': '脚本请求时间',
        'dealTime': '归集成功时间',
        'remark': '备注',
        'createTime': '创建时间',
        'right': '操作',
        'deivceCode': '设备编号',
        'batchNo': '批次号',
        'cloudStatus': '归集方式',
    },
    'ban': {
        'accountNoTo': 'সংগ্রহ করা অ্যাকাউন্ট নাম্বার',
        'replacePayBillNo': 'সিরিয়াল সংখ্যা',
        'payWalletNo': 'প্রতিদানের ওয়ালেট নাম্বার',
        'walletType': 'ওয়ালেটের ধরন সংগ্রহ করা হচ্ছে',
        'status': 'অবস্থা',
        'payAmount': 'প্রদানের পরিমাণ',
        'balanceCardType': 'কার্ডের ধরন সংগ্রহ করার প্রয়োজন',
        'balanceCardToType': 'কার্ড টাইপে সংগ্রহ করুন',
        'merchantRequestTime': 'সংগ্রহের সময় আরম্ভ করো',
        'dealTime': 'সংগ্রহের সফল সময়',
        'walletRequestTime': 'স্ক্রিপ্ট অনুরোধের সময়',
        'remark': 'মন্তব্য',
        'createTime': 'সৃষ্টির সময়',
        'right': 'অপারেশন',
        'deivceCode': 'ডিভাইস নম্বর',
        'batchNo': 'ব্যাচ নম্বর',
        'cloudStatus': 'সংগ্রহ পদ্ধতি',
    }
}
//个户归集-钱包流水分页列表
const  verification ={
    'en': {
        'replacePayBillNo': 'Payment order number | Platform serial number',
        'walletSerialNo': 'E-wallet payment serial number Txid',
        'behalfAmount': 'Bank card or e-wallet balance',
        'payAmount': 'Payment amount',
        'payAmountTotal': 'Total amount of actual payment',
        'payFee': 'Pay commission',
        'status': 'status',
        'verificationStatus': 'Storage status',
        'soriginalData': 'Original analytic flow',
        'failure': 'remark',
        'dealTime': 'Transaction closing time',
        'createTime': 'Creation time',
        'right': 'Controls',
    },
    'zh': {
        'replacePayBillNo': '付款单号|平台流水号',
        'walletSerialNo': '电子钱包支付流水号Txid',
        'behalfAmount': '银行卡或电子钱包余额',
        'payAmount': '付款金额',
        'payAmountTotal': '实际付款总金额',
        'payFee': '支付手续费',
        'status': '状态',
        'verificationStatus': '入库状态',
        'soriginalData': '原始解析流水',
        'failure': '备注',
        'dealTime': '交易完成时间',
        'createTime': '创建时间',
        'right': '操作',
    },
    'ban': {
        'replacePayBillNo': 'প্ল্যাটফর্ম সিরিয়াল সংখ্যা',
        'walletSerialNo': 'ইলেক্ট্রোনিক ওয়ালেট সিরিয়াল নাম্বার টিক্সিড',
        'behalfAmount': 'ব্যাংক কার্ড অথবা ইলেক্ট্রোনিক ওয়ালেট ব্যালেন্স',
        'payAmount': 'প্রতিদান',
        'payAmountTotal': 'প্রকৃত মোট পুরস্কারের পরিমাণ',
        'payFee': 'কমিশন',
        'status': 'অবস্থা',
        'verificationStatus': 'সংরক্ষণের অবস্থা',
        'soriginalData': 'প্রাথমিক বিশ্লেষণের প্রবাহ',
        'failure': 'নোট',
        'dealTime': 'ট্রান্সফেন্স পূর্ণ সময়',
        'createTime': 'সৃষ্টির সময়',
        'right': 'অপারেট করো',
    }
}
//代收代付汇总
const  collectionReplacePay ={
    'en': {
        'day': 'Request date',
        'replacePayCount': 'Pay for orders',
        'replacePayAmount': 'Amount paid',
        'replacePayFee': 'commission',
        'collectionCount': 'Collection order number',
        'collectionAmount': 'Amount collected',
        'collectionFee': 'Collection commission',
        'collectionSucRate': 'Collection success rate',
        'replaceSucRate': 'Success rate of payment'
    },
    'zh': {
        'day': '请求日期',
        'replacePayCount': '代付订单数',
        'replacePayAmount': '代付金额',
        'replacePayFee': '代付手续费',
        'collectionCount': '代收订单数',
        'collectionAmount': '代收金额',
        'collectionFee': '代收手续费',
        'collectionSucRate': '代收成功率',
        'replaceSucRate': '代付成功率'
    },
    'ban': {
        'day': 'DATE',
        'replacePayCount': 'টাকা নির্দেশের সংখ্যা',
        'replacePayAmount': 'প্রক্সি প্রতিদানের পরিমাণ',
        'replacePayFee': 'প্রক্সি প্রতিদান সার্ভিস ফি',
        'collectionCount': 'সংগ্রহিত আদেশের সংখ্যা',
        'collectionAmount': 'সংগ্রহের পরিমাণ',
        'collectionFee': 'হ্যান্ডিং ফির সংগ্রহ',
        'collectionSucRate': 'সংগ্রহের সফল হার',
        'replaceSucRate': 'প্রক্সি প্রতিদানের সফল হার'
    }
}
//客户公告
const notice = {
    'en': {
        'noticeText': 'Announcement content',
        'merchantType': 'Merchant announcement type',
        'noticeType': 'Announcement type',
        'updateTime': 'Update time',
        'createTime': 'Creation time',
        'right': 'manipulate',
    },
    'zh': {
        'noticeText': '公告内容',
        'merchantType': '商户公告类型',
        'noticeType': '公告类型',
        'updateTime': '更新时间',
        'createTime': '创建时间',
        'right': '操作',

    },
    'ban': {
        'noticeText': 'বিজ্ঞাপনের ধরন',
        'merchantType': 'বিজ্ঞাপনের ধরন',
        'noticeType': 'বিজ্ঞাপনের ধরন',
        'updateTime': 'সময় আপডেট করো',
        'createTime': 'সৃষ্টির সময়',
        'right': 'অপারেশন',

    }
};


//代理户钱包日统计
const dailyStatistics={
    'en': {
        'accountPhone': 'Agent account number',
        'b2bReceive': 'B2B collection amount today',
        'b2bReceiveTransactionCount': 'Number of B2B collections today',
        'b2bSend': 'B2B payment amount today',
        'b2bSendTransactionCount': 'Number of B2B payments today',
        'cashBackReward': 'Cash back incentive',
        'cashBackRewardTransactions': 'Number of cash back transactions awarded',
        'cashIn': 'Today\'s expenditure',
        'cashOut': 'Income today',
        'cashinCommission': 'কমিশন আজকে টাকা দিয়েছে',
        'cashinTransactionCount': 'Number of expenditures today',
        'cashoutCommission': 'Commission earned today',
        'cashoutTransactionCount': 'Number of earnings today',
        'currentBalance': 'Current balance (total)',
        'dayCommission': 'Commission (rebate) Amount (total)',
        'dayTransactionCount': 'Number of transactions Today (total)',
        'lastUpdate': 'Balance last updated time',
        'reportTime': 'Script escalation time',
        'reverseCommission': 'Reverse commission (Cash reward)',
        'reverseCommissionCount': 'Reverse commission number',
        'startingBalance': 'The amount before today\'s transaction',
        'todayTransactions': 'The total amount traded today',
        'walletType': 'Wallet type',
    },
    'zh': {
        'accountPhone': '代理户账号',
        'b2bReceive': '今日B2B收款金额',
        'b2bReceiveTransactionCount': '今日B2B收款条数',
        'b2bSend': '今日B2B付款款金额',
        'b2bSendTransactionCount': '今日B2B付款条数',
        'cashBackReward': '现金返还奖励',
        'cashBackRewardTransactions': '现金返还交易奖励数量',
        'cashIn': '今日支出',
        'cashOut': '今日收入',
        'cashinCommission': '今日支出佣金',
        'cashinTransactionCount': '今日支出笔数',
        'cashoutCommission': '今日收入佣金',
        'cashoutTransactionCount': '今日收入笔数',
        'currentBalance': '当前余额(总)',
        'dayCommission': '佣金(回扣)金额（总）',
        'dayTransactionCount': '今日交易条数（总）',
        'lastUpdate': '余额最后更新时间',
        'reportTime': '脚本上报时间',
        'reverseCommission': '反向佣金(现金回馈奖励)',
        'reverseCommissionCount': '反向佣金条数',
        'startingBalance': '今日发生交易之前的金额',
        'todayTransactions': '今日交易的总金额',
        'walletType': '钱包类型',
    },
    'ban': {
        'accountPhone': 'প্রক্সি অ্যাকাউন্ট',
        'b2bReceive': 'আজকের বি২বি পরিমাণ',
        'b2bReceiveTransactionCount': 'আজকে বি২B গ্রহণের সংখ্যা',
        'b2bSend': 'আজকের বি২বি পরিমাণ',
        'b2bSendTransactionCount': 'আজকের বি২বি পুরস্কার রেকর্ড',
        'cashBackReward': 'টাকা পুনরায় পুরস্কার করো',
        'cashBackRewardTransactions': 'টাকা বিনিময় পুরস্কারের সংখ্যা',
        'cashIn': 'আজকের খরচ',
        'cashOut': 'আজকের আয়',
        'cashinCommission': 'Commission paid today',
        'cashinTransactionCount': 'আজকের খরচ গণনা',
        'cashoutCommission': 'আজকের আয় কমিশন',
        'cashoutTransactionCount': 'আজকের প্রকাশিত অনুবাদ',
        'currentBalance': 'বর্তমান ব্যবস্থা (মোট)',
        'dayCommission': 'কমিশন (পুনরায়) পরিমাণ (মোট)',
        'dayTransactionCount': 'আজকের মোট সংখ্যার সংখ্যা',
        'lastUpdate': 'ব্যালেনের শেষ আপডেটের সময়',
        'reportTime': 'স্ক্রিপ্ট মুছে ফেলার সময়',
        'reverseCommission': 'কমিশন ফিরিয়ে নিন (টাকা পুরস্কার)',
        'reverseCommissionCount': 'কমিশন বিনিময়ের সংখ্যা',
        'startingBalance': 'ট্রান্সপার্সিং সংঘটিত হওয়ার আগের পরিমাণ',
        'todayTransactions': 'আজকের বিনিময়ের মোট পরিমাণ',
        'walletType': 'ওয়ালেটের ধরন',
    }
}